<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <UserSecretsId>ashlar-sample-aspnetcore</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <ProjectReference Include="..\..\src\Ashlar\Ashlar.csproj" />
    <ProjectReference Include="..\..\src\Ashlar.AspNetCore\Ashlar.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Ashlar.Passkeys\Ashlar.Passkeys.csproj" />
    <ProjectReference Include="..\..\src\Ashlar.Postgres\Ashlar.Postgres.csproj" />
  </ItemGroup>
</Project>
