<Project>

  <Import Project="..\Directory.Build.targets" />

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <None Include="$(MSBuildThisFileDirectory)coverlet.mtp.appsettings.json" Link="coverlet.mtp.appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
