<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Ashlar\Ashlar.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Schema\Scripts\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ashlar.Postgres.Tests" />
  </ItemGroup>

</Project>
