<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Ashlar\Ashlar.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Schema\Scripts\*.sql" />
  </ItemGroup>
</Project>
