<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ashlar.ProviderContractTests\Ashlar.ProviderContractTests.csproj" />
    <ProjectReference Include="..\Ashlar.Testing\Ashlar.Testing.csproj" />
    <ProjectReference Include="..\..\src\Ashlar.Sqlite\Ashlar.Sqlite.csproj" />
  </ItemGroup>

</Project>
